import { GluegunToolbox } from 'gluegun'

module.exports = {
  name: 'init',
  alias: ['i'],
  description: 'Initialize a new Revolutionary UI project workspace',
  run: async (toolbox: GluegunToolbox) => {
    const {
      parameters,
      prompt,
      filesystem,
      print,
      strings,
    } = toolbox

    print.info('Initializing new Revolutionary UI project...')
    // Determine project name
    let name = parameters.first
    if (!name) {
      const response = await prompt.ask({
        type: 'input',
        name: 'name',
        message: 'Project name',
      })
      name = response.name
    }

    const targetDir = name
    if (filesystem.exists(targetDir)) {
      print.error(`Directory '${targetDir}' already exists. Aborting.`)
      return
    }

    // Create project directories
    filesystem.dir(targetDir)
    filesystem.dir(`${targetDir}/components`)
    filesystem.dir(`${targetDir}/patterns`)
    filesystem.dir(`${targetDir}/hooks`)

    // Write basic config and README
    const config = { name, version: '0.1.0' }
    filesystem.write(
      `${targetDir}/revui.config.json`,
      JSON.stringify(config, null, 2)
    )
    filesystem.write(
      `${targetDir}/README.md`,
      `# ${name}\n\nGenerated by Revolutionary UI CLI init.`
    )

    print.success(`Project '${name}' initialized.`)
    print.info(`cd ${targetDir} to get started.`)
  },
}
